---
# Copyright (c) 2015 SONATA-NFV [, ANY ADDITIONAL AFFILIATION]
# ALL RIGHTS RESERVED.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Neither the name of the SONATA-NFV [, ANY ADDITIONAL AFFILIATION]
# nor the names of its contributors may be used to endorse or promote 
# products derived from this software without specific prior written 
# permission.
# 
# This work has been performed in the framework of the SONATA project,
# funded by the European Commission under Grant number 671517 through 
# the Horizon 2020 and 5G-PPP programmes. The authors would like to 
# acknowledge the contributions of their colleagues of the SONATA 
# partner consortium (www.sonata-nfv.eu).
# encoding: utf-8
development: &common_settings
  services:
    packages:
      url: http://localhost:5100
      model: PackageManagerService
      environment: PACKAGE_MANAGEMENT_URL
    services:
      url: http://localhost:5300
      model: ServiceManagerService
      environment: SERVICE_MANAGEMENT_URL
    functions:
      url: http://localhost:5400
      model: FunctionManagerService
      environment: FUNCTION_MANAGEMENT_URL
    records:
      url: http://localhost:5500
      model: RecordManagerService
      environment: RECORD_MANAGEMENT_URL
    licences:
      url: http://sp.int3.sonata-nfv.eu:5900
      model: LicenceManagerService
      environment: LICENCE_MANAGEMENT_URL
    vims:
      url: http://localhost:5600
      model: VimManagerService
      environment: VIM_MANAGEMENT_URL
    wims:
      url: http://localhost:5600
      model: WimManagerService
      environment: VIM_MANAGEMENT_URL
    kpis:
      url: http://localhost:5200
      model: KpiManagerService
      environment: KPI_MANAGEMENT_URL
    users:
      url: http://localhost:5700
      model: User
      environment: USER_MANAGEMENT_URL
    micro-services:
      url: http://localhost:5700
      model: MicroService
      environment: USER_MANAGEMENT_URL
    catalogue:
      url: http://sp.int3.sonata-nfv.eu:4002/catalogues/api/v2
      model: Catalogue
      environment: CATALOGUES_URL
    metrics:
      url: http://sp.int3.sonata-nfv.eu:8000/api/v1
      model: Metric
      environment: METRICS_URL
    validator:
      #url: http://sp.int3.sonata-nfv.eu:8000/api/v1
      model: Validator
      environment: VALIDATOR_URL
  level: debug
  defaults:
    page:
      size: 10
      number: 0
    throttle:
      max_value: 1
      value: 1
      unit: minute

test:
  <<: *common_settings

integration:
  <<: *common_settings

qualification:
  <<: *common_settings

demonstration:
  <<: *common_settings
 