---
resources:
  - catalogue
  - repositories
  - gatekeeper
  - monitoring

groups:
    developers: developer
    customers: customer
    admins: admin

paths:
    catalogue:
        services:
                 GET: read
                 POST: write
                 PUT: write
                 DEL: write
        functions:
                 GET: read
                 POST: write
                 PUT: write
                 DEL: write
        packages:
                 GET: read
                 POST: write
                 PUT: write
                 DEL: write

    repositories:
        requests:
                 GET: read
                 POST: execute
        instances:
                 GET: read
                 POST: write
        vims:
                 GET: read

    gatekeeper:
        resource:
                 GET: read
                 POST: write
                 PUT: write
                 DEL: write
    monitoring:
        resource:
                 GET: read
                 POST: write
                 PUT: write
                 DEL: write