development:
  sessions:
    default:
      database: user-management
      hosts:
      - mongo-gtk:27017

production:
  sessions:
    default:
      database: user-management
      hosts:
      - mongo-gtk:27017

test:
  sessions:
    default:
      database: user-management
      hosts:
      - mongo-gtk:27017